### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/storefront-qwik-starter#120]
I tried uploading a file but it didn't work with GraphQLs generic-sdk. It took me a full day to debug this. So far I haven't gotten to a way to do this via generic-sdk but managed to find a workaround (below):
- My Codegen config looks something like this
```yml
overwrite: true
schema:
  - "https://example.com/api"

  # This is the additional schema extension that would be present if
  # the Stripe playment plugin is enabled on the Vendure server. Added
  # manually here to allow codegen to work regardless.
  - "type Mutation { createStripePaymentIntent: String }"

documents:
  - "src/providers/shop/**/*.{ts,tsx}"
  - "!src/generated/*"
generates:
  src/generated/graphql-shop.ts:
    config:
      enumsAsConst: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-generic-sdk
  src/generated/schema-shop.graphql:
    plugins:
      - schema-ast
```

- The mutation to upload a file is simple, and I don't think the issue is there since I tested uploading files via Altair GraphQL Client which allows uploading files. That worked fine without issues.
```
// Note - I use qwik's noSerialize since this will be in a store, to be used across routes client-side.
// I tried uploading the blob before using noSerialize, same issue (below)
const imageBlob = noSerialize(await canvasToBlob(canvasEl.value!));
const filename = `preview_${new Date().getTime()}.png`;
const assetFile = new File([imageBlob as BlobPart], filename, { type: 'image/png' });
const res = await uploadAssetsMutation({
  input: { assets: [assetFile], someCustomId: customId.id }
  }, {
  apiUrl: 'https://example.com/api',
  channelToken: 'sample-channel-token'
});
``` 
canvasToBlob is just a helper function to use async-await instead of a callback with the canvas toBlob() function:
```
function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) {
        // if blob creation was successful
        resolve(blob);
      } else {
        // if blob creation failed
        reject(new Error('canvas.toBlob() error'));
      }
    });
  });
}
```

The error I get is as follows

```
{1 item
  "errors": [1 item
    0:{. 2 items
      "message":"Variable "$input" got invalid value {} at "input.assets[0]"; Upload value invalid."
      "extensions":{1 item
        "code":"BAD_USER_INPUT"
        }
      }
    ]
}
```
** WORKAROUND **
I could get around this by using the Apollo upload client
```
import { ApolloClient, InMemoryCache } from '@apollo/client/core';
const UPLOAD_MUTATION = gql`
  mutation uploadPreview($input: SomeInput!) {
    uploadPreviewAssets(input: $input) {
      id
      width
      height
      name
      preview
      focalPoint {
        x
        y
      }
    }
  }
`;

const client = new ApolloClient({
  link: createUploadLink({
    uri: 'https://example.com/api',
    headers: { "vendure-token": 'some-token'}
  }),
  cache: new InMemoryCache(),
});

client
  .mutate({
    mutation: UPLOAD_MUTATION,
    variables: {
      input: {
        assets: [assetFile],
        someEntityId: someEntity.id,
      },
    },
  })
  .then((result) => console.log('uploaded preview image:', result))
  .catch((error) => console.error('Couldnt upload preview img:', error));
```

I looked through the-guild.dev for solutions but couldn't find any that worked. Anyone else facing issues with uploads here?
